services:
  backend:
    build: ./Backend-LCode
    container_name: fastapi-backend
    ports:
      - "9000:8000"
    volumes:
      - ./Backend-LCode:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:notSecureChangeMe@db:3306/lcode_db
    restart: always

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:
